import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const origin=JSON.parse(fs.readFileSync('site-config.json','utf8')).origin?.replace(/\/$/,'');
const metadata=JSON.parse(fs.readFileSync('seo-pages.json','utf8'));
const pages=fs.readdirSync(root,{recursive:true,withFileTypes:true}).filter(e=>e.isFile()&&e.name.endsWith('.html')&&!e.parentPath.includes('node_modules')&&!e.parentPath.includes('.git')).map(e=>path.join(e.parentPath,e.name));
if(origin && (!/^https:\/\/[a-z0-9.-]+$/i.test(origin)||origin.includes('example')))throw Error('Set the confirmed HTTPS domain only.');
const urls=[];
for(const file of pages){let h=fs.readFileSync(file,'utf8');const rel=path.relative(root,file).replaceAll('\\','/');const route=rel==='index.html'?'':path.dirname(rel)+'/';const prefix=rel.includes('/')?'../':'./';const imageTag=[...h.matchAll(/<img[^>]*src="[^" ]*images\/([^" ]+\.webp)"[^>]*>/g)][0];const image=rel==='index.html'?'hero-حداد-مكة-أمجد.webp':imageTag?.[1]||'amjad-wordmark-preview.png';
const page=metadata[route.replace(/\/$/,'')];
if(page){h=h.replace(/<title>[^<]+<\/title>/,`<title>${page.title}</title>`).replace(/name="description" content="[^"]*"/,`name="description" content="${page.description}"`).replace(/property="og:title" content="[^"]*"/,`property="og:title" content="${page.title}"`).replace(/property="og:description" content="[^"]*"/,`property="og:description" content="${page.description}"`).replace(/name="twitter:(?:title|description)" content="[^"]*"/g,m=>m.startsWith('name="twitter:title')?`name="twitter:title" content="${page.title}"`:`name="twitter:description" content="${page.description}"`);
if(page.detail){let seen=new Set();h=h.replace(/<p>([^<]+)<\/p>/g,(tag,text)=>{if(seen.has(text)&&text.length>90&&!text.includes('مكة المكرمة —'))return `<p>${page.detail}</p>`;seen.add(text);return tag;});}}
h=h.replace(/<!-- Canonical[^>]*-->/g,'').replace(/<meta property="og:(?:image(?::[^" ]+)?|url)"[^>]*>/g,'').replace(/<meta name="twitter:(?:image|title|description)"[^>]*>/g,'').replace(/<link rel="canonical"[^>]*>/g,'').replace(/<link rel="apple-touch-icon"[^>]*>/g,'').replace(/<link rel="icon"[^>]*type="image\/png"[^>]*>/g,'');
const url=origin?origin+'/'+route:null;
if(rel!=='404.html'&&origin){h=h.replace('noindex, follow, max-image-preview:large','index, follow, max-image-preview:large');urls.push(url);h=h.replace('</head>',`<link rel="canonical" href="${url}"><meta property="og:url" content="${url}"></head>`);}
h=h.replace('</head>',`<meta property="og:image" content="${origin?origin+'/':prefix}images/${image}"><meta name="twitter:image" content="${origin?origin+'/':prefix}images/${image}"><link rel="icon" href="${prefix}images/favicon-48.png" type="image/png" sizes="48x48"><link rel="apple-touch-icon" href="${prefix}images/apple-touch-icon.png" sizes="180x180"></head>`);
const imageWidth=image==='amjad-wordmark-preview.png'?780:Number(imageTag?.[0].match(/width="(\d+)"/)?.[1]||2048);const imageHeight=image==='amjad-wordmark-preview.png'?264:Number(imageTag?.[0].match(/height="(\d+)"/)?.[1]||768);const imageAlt=image==='amjad-wordmark-preview.png'?'amjad':imageTag?.[0].match(/alt="([^"]*)"/)?.[1]||'أعمال الحديد';
h=h.replace('</head>',`<meta property="og:image:type" content="${image.endsWith('.png')?'image/png':'image/webp'}"><meta property="og:image:width" content="${imageWidth}"><meta property="og:image:height" content="${imageHeight}"><meta property="og:image:alt" content="${imageAlt}"></head>`);
if(page&&!h.includes('name="twitter:title"'))h=h.replace('</head>',`<meta name="twitter:title" content="${page.title}"><meta name="twitter:description" content="${page.description}"></head>`);
if(rel==='اعمالنا/index.html')h=h.replace('أبواب وشبابيك ودرابزين وأعمال خارجية','نماذج للأبواب والشبابيك والأعمال المعدنية').replace('حلوق معدنية مفصلة حسب الفتحة','تفصيل حلوق الأبواب حسب الفتحة');
if(rel==='اعمالنا/index.html'){const serviceRoutes=[['أبواب-حديد','ابواب-حديد'],['شبابيك-حديد','شبابيك-حديد'],['سلالم-ودرابزين','درابزين-وسلالم'],['برجولات-حديد','برجولات'],['تركيب-قرميد','قرميد'],['ديكور-حديد','ديكور-حديد'],['هناجر-حديد','هناجر-معدنية']];h=h.replace(/<figure class="gallery-card[^>]*>[\s\S]*?<\/figure>/g,figure=>{if(figure.includes('<figcaption><a'))return figure;const route=serviceRoutes.find(([token])=>figure.includes(token))?.[1];return route?figure.replace(/<figcaption>([^<]+)<\/figcaption>/,`<figcaption><a href="../${route}/">$1</a></figcaption>`):figure;});}
if(rel==='من-نحن/index.html')h=h.replace('صور حقيقية للخدمات','نماذج للخدمات').replace('هوية لخدمة أعمال الحديد والألمنيوم حسب الطلب','أمجد يقدم أعمال الحديد والألمنيوم حسب الطلب');
if(origin)h=h.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,(_,json)=>{const data=JSON.parse(json);function walk(o){if(!o||typeof o!=='object')return;for(const [key,v]of Object.entries(o)){if(typeof v==='string'&&key==='item'&&v.startsWith('.')){const target=path.relative(root,path.resolve(path.dirname(file),v)).replaceAll('\\','/');o[key]=origin+'/'+(target==='index.html'?'':target.replace(/index.html$/,''));}else if(key==='@id'&&typeof v==='string'&&v.startsWith('#'))o[key]=origin+'/'+v;else walk(v);}if(o['@type']==='WebSite'||(Array.isArray(o['@type'])&&o['@type'].includes('Organization')))o.url=origin+'/';if(o['@type']==='Service')o.url=url;}walk(data);return `<script type="application/ld+json">${JSON.stringify(data)}</script>`;});
if(origin)h=h.replace(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g,(_,json)=>{const data=JSON.parse(json);const businessId=origin+'/#business';function normalize(o){if(!o||typeof o!=='object')return;const types=Array.isArray(o['@type'])?o['@type']:[o['@type']];if(types.some(t=>['Organization','HomeAndConstructionBusiness','LocalBusiness'].includes(t))){Object.assign(o,{'@type':['LocalBusiness','HomeAndConstructionBusiness'],'@id':businessId,name:'أمجد',alternateName:'Amjad',url:origin+'/',telephone:'+966538341379',email:'alahmramgad@gmail.com',areaServed:{'@type':'City','name':'مكة المكرمة'}});if(rel==='index.html')Object.assign(o,{logo:{'@type':'ImageObject',url:origin+'/images/amjad-wordmark-preview.png',width:780,height:264},image:origin+'/images/hero-حداد-مكة-أمجد.webp'});}
if(types.includes('WebSite'))Object.assign(o,{'@id':origin+'/#website',url:origin+'/',name:'أمجد',alternateName:'Amjad'});
if(types.includes('FAQPage')){const answers=[...h.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').matchAll(/<div id="faq-\d+"[^>]*><p>([^<]+)<\/p>/g)].map(m=>m[1]);if(answers.length===(o.mainEntity??[]).length)o.mainEntity.forEach((question,i)=>{question.acceptedAnswer.text=answers[i];});}
if(types.includes('Service')){o['@id']=url+'#service';o.url=url;o.provider={'@type':'HomeAndConstructionBusiness','@id':businessId,name:'أمجد',alternateName:'Amjad',url:origin+'/',telephone:'+966538341379',email:'alahmramgad@gmail.com',areaServed:{'@type':'City',name:'مكة المكرمة'}};}
for(const value of Object.values(o))if(value&&typeof value==='object')normalize(value);}
normalize(data);return `<script type="application/ld+json">${JSON.stringify(data)}</script>`;});
h=h.replace(/href="\.\/index\.html([#?][^"]*)?"/g,(_,suffix='')=>`href="./${suffix}"`).replace(/href="\.\.\/index\.html([#?][^"]*)?"/g,(_,suffix='')=>`href="../${suffix}"`).replace(/href="(\.\.?\/[^"?#]+)\/index\.html([#?][^"]*)?"/g,(_,base,suffix='')=>`href="${base}/${suffix}"`);
h=h.replace(/[ \t]+$/gm,'');fs.writeFileSync(file,h);}
fs.writeFileSync('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`<url><loc>${u}</loc><lastmod>2026-09-21</lastmod></url>`).join('\n')}\n</urlset>\n`);
if(origin)fs.writeFileSync('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log(origin?`Production SEO configured: ${urls.length} URLs`:'Staging SEO: awaiting confirmed Amjad domain');
